FROM php:7.4-fpm

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
  install-php-extensions gd xdebug pdo_mysql bz2

RUN install-php-extensions @composer

EXPOSE 9000
CMD ["php-fpm"]